### ISSUE TITLE
"Detached" mode?

### ISSUE THREAD

**Issue by ttscoff** [stefanXO/Tab-Manager-Plus#1]
It would be really great if I could move tabs between windows without Tab Manager closing and focusing the affected tab every time. Would it be possible to have the tab positioning take place in the background without closing the Tab Manager panel?

**Comment by mastef** [comment]
@ttscoff Yeah, I think that sounds like a good idea

**Comment by ttscoff** [comment]
Huh, I swear it wasn't working that way before, but it is now. Might've been something in my own config. Great now 😀
