### ISSUE TITLE
any place to rename the window?

### ISSUE THREAD

**Issue by yuxh** [stefanXO/Tab-Manager-Plus#10]
I could not find the place to rename the Window, could I?

**Comment by mastef** [comment]
Yes, press on the colors icon. You'll be able to select a color and name the window.
![image](https://user-images.githubusercontent.com/762297/58448210-59b62280-8131-11e9-89a0-d6fd1901bfa3.png)

If you don't see the icon, make sure "Show action buttons" is enabled in the options.

**Comment by yuxh** [comment]
thanks,I find it ,but I think this function shouldn't be categoried into "colorize the window", maybe clicking  on the window title dirctly to rename is better

**Comment by mastef** [comment]
Yes @yuxh, you are right
