### ISSUE TITLE
Chrome TMP v5.1.6 CRX Header Invalid Install Error

### ISSUE THREAD

**Issue by Bamajon1974** [stefanXO/Tab-Manager-Plus#101]
Chrome v83, Tab Manager Plus v5.1.6, when installing the crx file from GitHub, gives an error message: Package is invalid: CRX_HEADER_INVALID when dragging and dropping to the chrome://extensions page. 

Can you upload the crx file to the Chrome Store please if CRX file cannot be repaired?

Thanks!

**Comment by mastef** [comment]
@Bamajon1974 you can try drag & drop .zip version instead.

I was able to replicate the error with .crx - with the .zip it did work.

**Comment by Bamajon1974** [comment]
Ok I could load the extension by either loading the unpacked ZIP extension or dragging the ZIP file to the extensions page. However, I this Developer Mode extension warning box with the recommendation to disable the extension appears every time Chrome is launched. How do you permanently disable the warning? There doesn't seem to be any straightforward way to do do in settings, extensions or flags.

**Comment by mastef** [comment]
@Bamajon1974 actually I never encountered this 🤔 

Apparently it won't show up with a dev version ( maybe neither with Chrome Canary? ) https://www.google.com/chrome/dev/?extra=devchannel ( from https://stackoverflow.com/a/47435357/10728554 )

Is there some specific update that you're looking for? Most updates in the last 3 versions were for Firefox.

**Comment by Bamajon1974** [comment]
I didn't realize the updates were mostly for Firefox. I saw update extension files for both browsers and thought the updates applied equally. 

However, the Developer Mode extension warning seems to apply only to stable builds of Chrome. I have read about it and there doesn't seem to be any way to disable. Have you figured out a way to bypass the warning box or does the extension have to be signed by the Chrome store to remove? I ask because I run a couple of other extensions that suffer the same annoyance.

**Comment by mastef** [comment]
I'm sorry, I'm not familiar with that warning and how to solve it. I'm using Chrome Canary personally and it doesn't seem to appear there.

I will be pushing an updated TMP version to the Chrome webstore soon. Their long approval process makes me avoid unnecessary updates for Chrome, as they cannot be rolled back/fixed quickly enough. A major annoyance.

**Comment by Bamajon1974** [comment]
Ahhh, so is that why Firefox add-ons are usually updated much sooner than Chrome extensions? The long approval process?

**Comment by mastef** [comment]
@Bamajon1974 yes - the Chrome webstore sometimes needs 10-14 days to release an update. Even if it was just some little text change. But now if that little update introduced a tiny error that I didn't catch, I have no way to release a hotfix neither. It will again be pending review as well. So that can take another 10-14 days...

E.g. one time I did a small css/design change with the search bar, and the button next to it disappeared due to that. An unintended consequence which took days to be resolved. It was just one line of code but the approval process really makes this tricky.

So I'm very wary about releasing bigger updates to the Chrome Webstore. I did a mistake once, and I think it lost the extension 1000s of users.

On the other hand if I release to Firefox, they have a more liberal algorithm. Nowadays the updates are released immediately. Initially it also took a while, but there might be a "trust" based system in place.

**Comment by mastef** [comment]
@Bamajon1974 actually it doesn't matter if the .crx would be valid. I just created a valid crx, and you wouldn't be able to load it in the chrome://extensions anyway. The extension would stay disabled with a warning that it wasn't downloaded from the Chrome webstore. 

You need to extract the zip file, and simply load the folder. ( Load unpacked extension ) That will work.

In any case, the 5.1.6 update is live in the Chrome webstore - so you don't need to load it manually any longer.

**Comment by Bamajon1974** [comment]
Great! Thank you! It is so much easier to install and run extensions through the Chrome Store. No invalid CRX header messages or annoying requests to disable unapproved extensions in Stable Chrome versions. 

I always wondered why Firefox addons seemed to be updated quicker than Chrome extensions. 

If you don't mind me asking, what exactly did you do to fix the crx extension to make the header valid? I run a couple of other extensions (like Viewhance in particular) that have the same error when installing manually (the author has had trouble getting approval to upload to the Chrome store). 

Thanks!

**Comment by mastef** [comment]
@Bamajon1974 the author shouldn't have any issues - all he has to do is upload a .zip file and the chrome store will create the .crx automatically.

As mentioned before, the .crx I created actually creates problems as new Chrome versions seem to block locally loaded .crx files. You have to unpack them, and then you can load the folder. So it doesn't really matter if you get a .zip file or .crx file, you have to unpack it anyway.

But if you want to create your own .crx archive you can look at https://www.npmjs.com/package/crx3

**Comment by Bamajon1974** [comment]
The author of Viewhance had issues with Chrome store rejecting his extension because of some privacy issues but the Firefox addon center had no issues. But I was able to extract the CRX file and load unpacked without an error but still triggering the Developer extension request to disable from the Stable build. Edge Chrome does the exact same thing. There used to be a group policy editor setting to whitelist the non-store approved extensions but it doesn't work anymore. All in all, the message is an annoyance and I can live with it. 

I tried a trick whereby you find the UniqueID of an extension, create a folder with that ID as a name in the C:\Users\[user_name]\AppData\Local\Google\Chrome\User Data\Default\Extensions directory, and extract the CRX file into that folder to try to bypass the developer extension nagging note and it worked briefly but I found the folder I created was automatically deleted. 

Which leads me to another question....where would one want to permanently copy the extracted CRX files to be loaded into Chrome, as opposed to a download or temporary directory?

**Comment by mastef** [comment]
I really wouldn't know, sorry - I just drag the folder into Canary and never get a warning or popup 🤔 

He should try re-submitting his extension - they added a few more fields to clearly clarify what an extension does. I had that happen to an extension of mine, and after filling out those fields it was re-approved without any code change whatsoever. 

Provided he doesn't use some 3rd party malware tracking, as extensions are currently overrun with that stuff.

**Comment by Bamajon1974** [comment]
Got it. Ok, thank you very much for your help!
