### ISSUE TITLE
Is there a way to active this extension when address bar is hidden?

### ISSUE THREAD

**Issue by viktor-ku** [stefanXO/Tab-Manager-Plus#123]
Hi! I am using Vivaldi and I have address bar and tabs hidden. Is there a way to active this extension?

**Comment by mastef** [comment]
You could try opening it with the default shortcut : 
```
"windows": "Ctrl+Shift+M",
"mac": "Command+Shift+M"
```
I am not familiar with Vivaldi, so not sure where the settings for these are. If you'd want to change it, I would look for shortcut settings either in : 
- `vivaldi://extensions` and then `Keyboard Shortcuts`
- or by trying this url : `vivaldi://extensions/shortcuts`

No guarantee this will work - that's how it works in Chrome.
