### ISSUE TITLE
Feature Request: Show tab resource usage

### ISSUE THREAD

**Issue by dembeck** [stefanXO/Tab-Manager-Plus#129]
### **IDEA:**

I would find it helpful if there was an option to show the resource usage of the different tabs. 

---

### USE CASE:

Sometimes when I have 100+ tabs open and Chrome has decided to use all of the memory, it's then time to close/save/discard a few of those tabs. I usually start with the tabs that think they need a 1gb+ of memory or are using 100% CPU, but that involves flipping back and forth between Tab-Manager-Plus and the Browser Task Manager to find them. It would be nice to just see the tabs, and the resource usage all on one screen.

---

### MOCKUP:

This is a rough idea of what I was thinking, but I think it would possibly look better if the resource info was on a second line below the page title and in a smaller font size. If it was an option to enable/disable the showing of resource usage, it should be possible to leave the height of the whole tab line very close to to what it is now by reducing vertical padding and the font size of the page title a bit, which would allow a similar number of tabs to be shown without scrolling.

![](https://user-images.githubusercontent.com/9568447/92984197-454c8500-f45d-11ea-982b-dd621e006ba7.png)

**Comment by mastef** [comment]
I would love to have this - was looking even into this myself a few months back - but I haven't found any APIs that expose this data for chrome extensions.

**Comment by grahamperrin** [comment]
> … flipping back and forth between Tab-Manager-Plus and the Browser Task Manager …

Does management in Google Chrome not allow closure of tabs? 

If not, you'll probably find a related request for enhancement at https://bugs.chromium.org/

----

Firefox 84.0.2 on FreeBSD-CURRENT: 

https://user-images.githubusercontent.com/192271/105801035-165c2900-5f90-11eb-8f60-fe00618e1130.mp4

**Comment by mastef** [comment]
I mean there's no extension api for tabs to show how much cpu/memory they consume - afaik
