### ISSUE TITLE
Feature Tracker: Save windows as sessions for later

### ISSUE THREAD

**Issue by mastef** [stefanXO/Tab-Manager-Plus#13]
An often requested feature / or misunderstanding about the term "Tab Manager Plus" is that we can save/restore sessions. This is nice for tab hoarders, and for people wanting to save RAM for later. Also for people who don't like the bookmark system.

So currently I'm testing a feature that will allow you to save windows with all the tabs as a session - so you can re-open the same window later on : 

![image](https://user-images.githubusercontent.com/762297/63566263-965db280-c596-11e9-84fd-1d78afc9e177.png)

A few caveats of the current approach : 
- `The tab history is lost`, so when you re-open a window from a session, it's only a window with X tabs that is restored. None of the tabs retain history information ( back button ). I can't find a solution to this issue currently.
- Since `chrome.storage.sync` is limited in size, the storage of the sessions would only be in the local browser - `chrome.storage.local`. I'm a little bit afraid of this approach, because if your Chrome runs into some issue ( e.g. out of disk space, corrupted browser ), you might lose a lot of important sessions that you saved for later
   - maybe add an export/import backup feature
   - or sync outside chrome.storage.sync ( firebase / own account system ? )
- The re-opened tabs are `fresh new tabs`. So if you typed in some form data ( like a comment ), and then saved the session - then restored it later on - that form data would be empty. Similar to the tab history issue above. Don't know a solution currently.
- `Drag & drop` in the session windows is currently `disabled`. The way the data is shown on the screenshot may suggest that you can just drag & drop tabs like usual and between each other, but currently that's not there.
- Should saving a session for later close the open window automatically? ( Currently : no )
- Should re-opening a session delete the session automatically? ( Currently : no )
- Easy to delete a session irrevocably by pressing the red X button
  - maybe add a "trash" that keeps deleted sessions for a few more days
  - or a popup to confirm session deletion ( annoying? )

**Comment by nollinvoyd** [comment]
I just discovered Tab Manager Plus.  Very nice.  I currently use Tab Session Manager, which focuses on a different approach.  

I'm guessing it's not possible, but combining the features (not possible?) of both would make the ultimate tab manager.  Going forward, I will probably use both in tandem.

Session Manager allows you to backup and restore sessions, not only within the browser, but externally as well.

**Comment by mastef** [comment]
@nollinvoyd this feature would kind of bring this.

1. When you're using Tab Session Manager and it restores a session - are you able to browse back within a tab? E.g. is the history of the tab preserved?
2. Backup/restore - is that simply to a .json ( or similar ) file?

Thanks

**Comment by waltersdmh** [comment]
Just in case this is useful:
An extension called "Tabs Outliner" does exactly this - keeps tab groups persist after a window is closed. 

I'm not a fan of the UI so prefer to use Tab Manager Plus, but it's worth checking out for an idea of scope.

**Comment by nollinvoyd** [comment]
> 
> 
> @nollinvoyd this feature would kind of bring this.
> 
>     1. When you're using Tab Session Manager and it restores a session - are you able to browse back within a tab? E.g. is the history of the tab preserved?
> 
>     2. Backup/restore - is that simply to a .json ( or similar ) file?
> 
The backup is an identical replica in every way, and restores as such.

The backup is a .json

**Comment by mastef** [comment]
> > > 1. When you're using Tab Session Manager and it restores a session - are you able to browse back within a tab? E.g. is the history of the tab preserved?
> The backup is an identical replica in every way, and restores as such.

When you're using Tab Session Manager and it restores a session - **are you able to browse back within a tab? E.g. is the history of the tab preserved?**

Could you please try

**Comment by nollinvoyd** [comment]
> 
> 
> > > > When you're using Tab Session Manager and it restores a session - **are you able to browse back within a tab? E.g. is the history of the tab preserved?**
> 

No.  I never noticed before.  I'm wondering if that could be remedied if the history files were included in the backup? Or if the history files were somehow synced, so if a backup was added to a current session, everything could be compiled.  

I'm just thinking out loud...no idea whether that's feasible.

**Comment by mastef** [comment]
@nollinvoyd No, I don't see a way to do this, and that's what I'm also worried about when introducing this feature.

1. I see a lot of negative reviews with session managers because people find surprises like these, when they need them the most. E.g. when somebody actually needed the tab history, and it's missing - very frustrating.

The issue is simply that the browser extension api doesn't allow you to fill the history ( from what I can see ). People are used to having the tab history, when they restore tabs with the Chrome history feature - but extensions don't have access to this it seems.

2. The other reason for bad reviews is lost data. And that's the other thing I'm really worried about before introducing this feature.


Like, I have this feature working locally here and I have no issues. But the above 2 points keep me from publishing it publicly.

**Comment by mastef** [comment]
Sessions are now shipped with version 5.0.4. It's disabled by default - you can enable it in the Tab Manager Plus options.

**Comment by mastef** [comment]
Backups to .json should be now shipped with the latest 5.0.8 version.
