### ISSUE TITLE
Saved windows do not restore

### ISSUE THREAD

**Issue by Reselka** [stefanXO/Tab-Manager-Plus#133]
Clicking the green check mark on a saved window to restore it instead opens a new window with only two tabs: a new tab and the first tab from the saved window. The original saved window remains in the saved window section and does not become active.

**Comment by RobbyTheBelgian** [comment]
Same here, Google Chrome Version 87.0.4280.66 (Official Build) (64-bit) on Ubuntu 18.04.5 LTS.

**Comment by mastef** [comment]
Could you kindly attach a .json file here so I could reproduce? You can remove any personal info from it ( urls and tab titles ) - just make sure that the changed file also produces the same bug for you.

Have you also tried restoring the session when the tab manager is open in its' own tab?

![image](https://user-images.githubusercontent.com/762297/100180555-f9ad6180-2f0a-11eb-879b-3de1206ec605.png)

**Comment by RobbyTheBelgian** [comment]
Running it in its own tab seems to work fine.

**Comment by crutley** [comment]
I'm trying this extension for the first time and seeing the same thing.  Restoring a saved window works from the sidebar or dedicated tab, but fails to restore most of the tabs when using the function from the pop-up window.

That said, I know it's an experimental feature.

A nice feature to add to window restoring would be the ability to lazy load all the tabs.

**Comment by nybbles** [comment]
I'm experiencing the same issue on Firefox

**Comment by mastef** [comment]
Moved to #179
