### ISSUE TITLE
[bug]popup mode is just not reliable

### ISSUE THREAD

**Issue by wadawada** [stefanXO/Tab-Manager-Plus#146]
Too many times it fails to close all the tabs that I selected
Instead, it closes a few tabs and the popup window closes, so I'll have to select tabs again
Ended up I need to open the extension in new tab to make sure it works

Also, something is wrong when I muliselect with use the "ctrl" key
It may eventually break the selections so I can't select too many tabs or I will have to select them again
kind of an annoying bug

**Comment by mastef** [comment]
Tracking part 1 in #179 

Can you please explain the 2nd bug? I don't fully understand what the problem is with the ctrl key. Which browser does this happen in?
