### ISSUE TITLE
Cannot change the shortcuts

### ISSUE THREAD

**Issue by zoukyle** [stefanXO/Tab-Manager-Plus#166]
Firefox version: 91.0
It seems that I cannot access the settings to change the shortcuts. Please fix. Thanks

**Comment by mastef** [comment]
> Firefox version: 91.0
> It seems that I cannot access the settings to change the shortcuts. Please fix. Thanks

Hi @zoukyle , have you read the description?
![image](https://user-images.githubusercontent.com/762297/129768459-25b16f5d-66a3-4bc4-8cc5-7ae20f3eb681.png)

Extension shortcuts are in a Firefox option that lists them for all Add-Ons at once. Go to `about:addons` and then click the cog.

![image](https://user-images.githubusercontent.com/762297/129768370-891c98bf-1afd-49aa-b23d-a6d0178a35c0.png)

![image](https://user-images.githubusercontent.com/762297/129768572-802a69c6-b7f6-40a1-b046-84d32e43a24e.png)

**Comment by zoukyle** [comment]
Thank you! Sorry that I missed the instruction. I thought it was a bug. Maybe you can remove the hyperlink because I was expecting it to show the config window after clicking the link.
