### ISSUE TITLE
Why is there no Help OR Support Contact in teh app itself????

### ISSUE THREAD

**Issue by decard123** [stefanXO/Tab-Manager-Plus#170]
... why do i have to spend 15 minutes to actual find this forum?

.... why is there no Help or documentation in the app? you know, duh, where it might be useful!

... why is there no support email or link in the app??? ditto above.

**Comment by Penguin-Guru** [comment]
I guess this is related to https://github.com/stefanXO/Tab-Manager-Plus/issues/148. Another option would be to link to a real-time communications channel, maybe Matrix, for users who are willing to help others.
