### ISSUE TITLE
Not All Saved Tabs Open.

### ISSUE THREAD

**Issue by Penguin-Guru** [stefanXO/Tab-Manager-Plus#175]
I have, on multiple occasions, saved window sessions with about 8-10 tabs and then later restored them. In all of these cases, only the first 2-3 tabs opened. The others do appear in the extension drop-down so I re-opened them in the new window by manually typing in the web address the extension shows, but this is a major nuisance.

Tab Manager Plus (for Chrome) 5.2.0.
Chromium 94.0.4606.81 (Official Build) (64-bit).
Linux 5.10.14.

Incidentally, it would be nice if there were a way to open specific tabs from the extension drop-down, or at least copy the web address for a specific tab into the system clipboard.

**Comment by mastef** [comment]
Have you tried opening the tab manager in its' own tab and then restoring
them?

Can you check if it opens all windows in that case?

**Comment by Penguin-Guru** [comment]
This does work. Thanks for the quick reply!

**Comment by mastef** [comment]
Moved the main issue to #179
