### ISSUE TITLE
Major bug: Windows names and colors are mixed up after browser restart

### ISSUE THREAD

**Issue by mastef** [stefanXO/Tab-Manager-Plus#178]
This is one of the biggest bugs of the extension. The reason for this is that window names and colors are saved based on the "window id" that we receive from the browser.

But once we restart the browser, the reopened windows may have mixed up "window id" parameters. So a window that had id 7855 before, may now have id 3422. Or some windows may have gotten the id of a previous window.

This seems like a frustrating issue.

Possibility of fixing it:

Every 10 or 60 seconds, make a snapshot of the open windows that have a custom name/custom color and snapshot what tabs they currently have saved.
Also try this on a browser close event, if possible.

Once a browser is re-opened, and somehow fully loaded ( Can we time this? Is there an event when a browser restoration is complete? ), or if a window is restored from history ( e.g. "re-open 7 closed tabs" ) - then compare against the saved list if it matches any of the windows we had saved, and restore the color/name to it.

This is a very funky logic, which is why this bug has been so prevalent.

Also how long should we remember a window name/color? What if a second window is opened with the same tabs... which window are we monitoring then for changes?

**Comment by uday-arrcus** [comment]
What is the plan to fix/resolve this issue?

**Comment by mastef** [comment]
Possibly fixed in [6.0.0](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/6.0.0)

**Comment by uday-arrcus** [comment]
Names are retained but the names are not retained with the actual windows/groups.

**Comment by mastef** [comment]
> Names are retained but the names are not retained with the actual windows/groups.

Waiting for 6.0.0 to be approved, as it's not live on the Chrome Web Store yet. You can download it directly from the releases page until then.

**Comment by mastef** [comment]
> Names are retained but the names are not retained with the actual windows/groups.

Waiting for 6.0.0 to be approved, as it's not live on the Chrome Web Store yet. You can download it directly from the releases page until then.

**Comment by uday-arrcus** [comment]
Thanks for the update, i use this extension in Firefox. Hope the latest version resolves the issue in Firefox as well. Could you point to the releases page from where i can download directly?
