### ISSUE TITLE
Major bug: Not all windows are re-opened / closed / etc in popup

### ISSUE THREAD

**Issue by mastef** [stefanXO/Tab-Manager-Plus#179]
This seems to happen from time to time. When trying to restore a window with - let's say - 10 tabs. The tab manager will only restore the first 3, because the popup closes in the mean time.

The same seems to happen when trying to close a window with a certain amount of tabs?

This bug doesn't happen when the tab manager is running in its' own window. It only happens in the popup, as the process is being killed by closing the popup.

To investigate: 
- why is this not finishing in the background tab?
- are we closing the tab manager ourselves, or is this done by the browser

Possible solution:
- save this action as an "intent", and run in background tab based on an interval

**Comment by mikedlr** [comment]
In a Firefox configuration with quite a number of extensions I find that no tabs whatsoever open. The workaround of opening in a separate tab works though. 

Firefox 103.0.1

**Comment by DataLoreQ** [comment]
I am experiencing this issue when trying to reopen saved windows.  I am running Firefox 111.0.1 (64-bit).  Whenever I try opening a saved window, I'm lucky if I get 8-12 tabs to open. Most often, it is only four tabs.

**Comment by DataLoreQ** [comment]
I am experiencing this issue when trying to reopen saved windows.  This is happening on both Firefox and Chrome.  Whenever I try opening a saved window, I'm lucky if I get 8-12 tabs to open. Most often, it is only four tabs.

If I open Tab Manager Plus in its own tab, then the saved windows will open.

**Comment by mastef** [comment]
Should be fixed in next version based on 7374bf6425a8ec80ff281583781540da652762db 17f69cfc7e60101895821d81e69e84b182aa2bb1 and 89b2fed8fb77d47ee29a96538ddf60cc1c614475

**Comment by mastef** [comment]
Should be fixed in [Firefox 5.2.3](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/5.2.3) and [Chrome 6.0.0](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/6.0.0)
