### ISSUE TITLE
Choose between popup, sidebar and window

### ISSUE THREAD

**Issue by bannmann** [stefanXO/Tab-Manager-Plus#18]
Instead of opening the extension in a popup, it should also be possible to open it in a sidebar or its own window. Please let the user choose the default mode to use when clicking the toolbar button in the extension options.

**Comment by mastef** [comment]
@bannmann I could make the extension open in a new window or as popup by default based on a setting. There is currently no easy way to open it as a side bar.

**Comment by mastef** [comment]
Ok @bannmann this should be now live with the latest [5.0.8 version](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/5.0.8). It was added in this commit https://github.com/stefanXO/Tab-Manager-Plus/commit/055f5f29a51c88fb51250a9ab6fa2407d7d6717e

It's already live in the [Mozilla Add-Ons store](https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/). Chrome Webstore should take a few more days as they flag nowadays everything for a review.

**Comment by bannmann** [comment]
Thanks a lot for implementing this, it works great!

**Comment by mastef** [comment]
@bannmann there was an issue with the new page, sometimes clicking on the icon wouldn't properly switch to it. That should be now resolved in `5.1.0`

Anything else I can do for you to get [that last 5th star](https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/reviews/1427817/)? 😄

**Comment by bannmann** [comment]
> Anything else I can do for you to get [that last 5th star](https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/reviews/1427817/)? 😄

LOL, thanks for reminding me to update my review. You earned it :-)

**Comment by keeganwitt** [comment]
Came across this while looking to see if someone had already asked for the sidebar feature: I don't see the option to display in sidebar.  Looking at the commit, it looks like that wasn't included.  Should I open a separate issue for this?

**Comment by mastef** [comment]
@keeganwitt yes please, right now there is no sidebar here
