### ISSUE TITLE
Regular Expression or Wild Card tab searchess

### ISSUE THREAD

**Issue by doychi** [stefanXO/Tab-Manager-Plus#194]
Searching thought the tabs, it would be handy to be able to use either regular expressions or wild card searches for tabs.  I know the primary feature of the extension is to find duplicates and more complicated searching moves away from this aim. However I think that being able to use a general tab search feature would broaden the usefulness of Tab Manager Plus.

**Comment by mastef** [comment]
I think currently search works with support for `AND` and `OR`. Adding regex is a bit overkill

**Comment by KieranDevvs** [comment]
> I think currently search works with support for `AND` and `OR`. Adding regex is a bit overkill

Not really overkill. If Ive got 50 YouTube tabs open, but I just want to close the 16 that are the home page, I cant easily filter that down.
A simple search for `https://www.youtube.com/$` would give me the exact search I want. 
URLs are complex.
