### ISSUE TITLE
Repository not up to date with published version

### ISSUE THREAD

**Issue by demetrios-koziris** [stefanXO/Tab-Manager-Plus#2]
Hi, it looks like version 4.8 is what's published in the google chrome store:
https://chrome.google.com/webstore/detail/tab-manager-plus/cnkdjjdmfiffagllbiiilooaoofcoeff/support?hl=en

Any idea when the repository (currently v4.6.1) will be brought up to date with the published version? 
Thanks!

**Comment by mastef** [comment]
Hey @demetrios-koziris - I've [pushed now the 4.8 update](https://github.com/stefanXO/Tab-Manager-Plus/commit/e54ef6fa4cdce862a825b41915cef1c8fbf2dd2d) to the github repository. Unfortunately I didn't have time yet to clean up the code properly, and didn't have the commits layed out step by step, so it's just a big push this time.

**Comment by demetrios-koziris** [comment]
Thanks a bunch!
