### ISSUE TITLE
Where did all the saved windows go?

### ISSUE THREAD

**Issue by JMazur1971** [stefanXO/Tab-Manager-Plus#213]
Hi.
I'm on Chrome Version 114.0.5735.134 (Official Build) (64-bit) using your extension. I had several saved windows with multiple tabs. The last saved on 6/21/23 circa 6:20 PM EDT before I rebooted the PC at 7-ish.

I'm not sure if Tab Manager Plus installed a new version, but all my saved windows seem to have vanished.  Is there some other spot I should be looking in?

Super frustrating....

**Comment by mastef** [comment]
There was no update. Maybe your local version got corrupted / storage cleared for some other reason.
