### ISSUE TITLE
Feature Request: Setting to display text along icons

### ISSUE THREAD

**Issue by igorlvicente** [stefanXO/Tab-Manager-Plus#215]
![image](https://github.com/stefanXO/Tab-Manager-Plus/assets/61885036/5234141f-7859-4158-a95e-fd7960af54ce)

Problem: I never know what the icons mean.
Context: I have a lot of space.
Solution to the problem: Add texts to the side of the icons. Make it a setting so people can opt-in only if they want.

**Comment by bigchakalaka** [comment]
you have a button to switch views down right
