### ISSUE TITLE
Update to manifest v3

### ISSUE THREAD

**Issue by igorlvicente** [stefanXO/Tab-Manager-Plus#216]
https://developer.chrome.com/docs/extensions/mv3/intro/

**Comment by wiwo192** [comment]
+1. This is urgent: Manifest v2 disablement is enabled in 2024-06, the change is gradually rolling out.

It is already stopping working in Chrome Canary build.

**Comment by mastef** [comment]
Fixed in [5.3.0](https://github.com/stefanXO/Tab-Manager-Plus/releases)
