### ISSUE TITLE
Feature request: Copy all links from a window to clipboard

### ISSUE THREAD

**Issue by aperz** [stefanXO/Tab-Manager-Plus#226]
Description:
- There is a button in the window pane to copy all tabs from the window as links to system clipboard.
- Maybe, e.g. in settings, a user can format how the links are exported (e.g. Markdown, plain text)

![image](https://github.com/stefanXO/Tab-Manager-Plus/assets/7249642/8a1da588-2140-4f10-a21f-ae567429300a)

As a user of a notes app, I would find it extremely useful :)

**Comment by mastef** [comment]
Sorry this is not in the scope of the tab manager.
You can try something like this https://chromewebstore.google.com/detail/export-tabs-as-text-file/odclbaijmmabcgcdaipkpkcmfkfifgea
