### ISSUE TITLE
No longer able to close tabs

### ISSUE THREAD

**Issue by drekye** [stefanXO/Tab-Manager-Plus#23]
With the latest update that required a renewal of permissions, there is a bug.  The close tab button (looks like a trash can) no longer works at all.  I've restarted chrome several times without any resolution.  Clicking the close tab button only scrolls you to the bottom of the tab list.

**Comment by mastef** [comment]
@drekye have you made sure that a tab is selected? ( right click )

You can also close tabs immediately with middle mouse click

**Comment by drekye** [comment]
The selection of the tab (right click) and using the middle mouse click both work, but it was just the closing of the active tab that wasn't working with the new update.  Thanks for the quick response!
