### ISSUE TITLE
Tab Group Name

### ISSUE THREAD

**Issue by dec-mail** [stefanXO/Tab-Manager-Plus#232]
And this is a really great highly functional easy to use Plugin, and i use it constantly.

But one time-wasting frustrating bug is - 
TMP keeps losing all the Tab Group names i carefully type and curate.
And there should be some Tab Group Names that are saved and used.

PS And it woud be really great for us and prob you, if you got together with another wonderful and complemetery Tab ext - Tab Stash, and, for example, Tab Stash could save the TMP Group names when saving them to Tab Stash.

**Comment by mastef** [comment]
Duplicate #178

**Comment by dec-mail** [comment]
WHY WAS THIS CLOSED AS 'COMPLETED??
as far as i am aware it is NOT 'completed'.
please advise.
