### ISSUE TITLE
Saved window animation change

### ISSUE THREAD

**Issue by frangkee** [stefanXO/Tab-Manager-Plus#235]
I have about 23 tabs open. One issue that appears to make the extension inefficient is that when I save a window it'll scroll to the bottom of the tab or popup window to show me the saved window. Time is wasted doing that animation/display. What will be more effective is to just show a toast or notification that'll tell you it is saved. Maybe even include a "Save and Close window" option.

**Comment by mastef** [comment]
How often do you save them per day that this becomes annoying ?

**Comment by frangkee** [comment]
At least two to three times a day. That really is depending on what kind of searches I end up doing in a day. Most of these saved tabs/windows are because I don't want these forgotten and I want to pick up where I left off. Which would explain why a save and close option would be great for my purpose.

**Comment by mastef** [comment]
I can only improve it by micro-seconds, there's no options on speed of scrolling here unfortunately. See bfc4b0dd7354c4d0dd48ba41effb85ef28fde075

**Comment by mastef** [comment]
What I can do is instant scroll if animations are disabled

**Comment by mastef** [comment]
Ok done in 843b1ced53bf060889e0cfb87dcd57804455475e

**Comment by frangkee** [comment]
I guess there's a little misunderstanding there. I meant to say the scrolling to the saved window/tab is unnecessary and I efficient. Maybe it's useful if you're going to rename, but you can also set it to ask for a rename when you opt to save. But for the most part I think users would just want to save for later.
