### ISSUE TITLE
It's really *very* sad that the Popup size is limited to 800x600

### ISSUE THREAD

**Issue by schittli** [stefanXO/Tab-Manager-Plus#26]
#### Thank you very much for this great Chrome Extension!,
it helps a lot to keep the big picture.

#### Suggestion: please don't limit the popup size
If a user would like to have a popup with 2000x1500 - why not?

My usual Chrome Session has 126 Tabs in 22 Windows and Tab-Manager-Plus could easily display all of them on my big screen. But because it limits the maximal Popup size, it's not so useful.

The usability of Tab-Manager-Plus is great for up to about 90 Tabs in maximal 6 Windows, 
but for more Tabs / Windows, the usability and overview get bad, because it imposes unnatural limits on itself.

So please allow (at least in advanced settings) to configure unlimited Popup sizes.

**Comment by mastef** [comment]
Hi @schittli I do fully agree!

I really wish we could increase the popup size further, but it's a hard limit set by both browsers ( Chrome and Firefox ):
- [chrome source code](https://cs.chromium.org/chromium/src/chrome/browser/ui/views/extensions/extension_popup.h?sq=package:chromium&dr=CSs&rcl=163367ca40a710ffca6b9ac02b58a4baa113d56e&g=0&l=54-55)
- [mozilla article](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing)
- [discussion on google groups](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/nJIWEuJpI3Y)
- [discussion on stackoverflow](https://stackoverflow.com/a/8983678/10728554)

I even wrote on google groups to extend this limitation, as I'm annoyed by it as well : [Allow extension popups sizes above 800x600](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/U08htZ7r6RY).

Any size above 800x600 is simply something that is being ignored by the browser, nothing this extension can do about.

What you can do instead is right clicking on the icon, and "Open in own tab" - then it will be as big as you wish.
![image](https://user-images.githubusercontent.com/762297/67615164-113f8580-f7f3-11e9-8122-13b2cbfc97b6.png)

**Comment by schittli** [comment]
Hello @mastef 
Thank you **very much** for your support!, 
opening the extension in its own Tab is a fast solution. (I also have changed the review in the Chrome Web Store.)

Thanks a lot, kind regards,
Thomas

**Comment by mastef** [comment]
@schittli thank you. Hopefully we'll be able to change it in the future.
