### ISSUE TITLE
Feature tracker : Keyboard shortcuts

### ISSUE THREAD

**Issue by mastef** [stefanXO/Tab-Manager-Plus#27]
Keyboard shortcuts :

Vertical view:
- left/right - jump to next/previous window  
- up/down - move to next/previous tab  
- shift+up/down - select next/previous tab

Other views:
- up/down - jump to next/previous window  
- left/right - move to next/previous tab  
- shift+left/right - select next/previous tab
  
General shortcuts:
- escape - clear selection & search term

**Comment by mastef** [comment]
Done in [5.1.0](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/5.1.0)

**Comment by wulymammoth** [comment]
I'm trying to search my open tabs without coming off my keyboard.

Is there a keyboard shortcut to open up the pop-up so that I can perform a search?

**Comment by mastef** [comment]
@wulymammoth the default shortcut is `Ctrl/Command+Shift+M`

In Chrome you can set it up here : `chrome://extensions/shortcuts`

In Firefox here you can set it up at `about:addons`, then click on that little icon in the top right corner and finally "Manage extension shortcuts"
![image](https://user-images.githubusercontent.com/762297/80553520-618ede80-89f4-11ea-919b-b404f6062669.png)
