### ISSUE TITLE
Why can't I create my own tab groups?

### ISSUE THREAD

**Issue by GreatAlfredini** [stefanXO/Tab-Manager-Plus#3]
======== copied from the chrome webstore ========

Ack! I apologize if it's there and I'm not seeing it, but it seems to be missing THE feature that would make it useful for my needs.

I would love to be able to create my own tab groups, as in the old, unrelated Firefox extension.

What in the world is the use of having a tab group with the same old 100+ tabs all in one place? Nothing. 

I already have something that shows me that - chrome itself. 

Don't need an extension to show me "Hey, here are your million unmanageable tabs, but hey, they're sorted by website".

People sort tabs not by website, but by function. For example, I'd love a tab group for, say, "Programming" into which I can manually move github, hackerrank, codeacademy, and youtube training videos. All different websites, but in one meaningful tab group. See what I mean?

Naturally, i would not want these tab groups to ruin the way I've got them arranged in chrome itself. Just something that allows me to create little tab groups, drag icons around, etc; same functionality as in the hardcoded not-so-useful "everything" single tab group you have now.

I was two seconds from uninstalling this extension and giving it a review, but it is sooooo close to what I need I thought I'd give this a shot.

And if the feature is already there, I do apologize for my rant, but then fer dog's sake, make it a lot easier to find and use.

======== someone replies with off-the-mark suggestions ========

I feel like my original post went completely unheard.

I feel very frustrated by this.  I went into some detail and explained as much as I could.

By "tab group" I mean, you know, a group of tabs.

A tab group that simply lists the tabs that are already in a chrome window is completely useless (to me).  That equals zero organizational capabilities.  I could just open that Chrome window to look at the tabs.  Or I could use any of a bunch of other extensions that list the tabs in a window.  Zero usefulness to the main functionality of this extension, then.

Yes, I know I can colorize tab groups in the popup. This does absolutely nothing to group them the way I described.

Giving the tab group, aka the chrome window, a name does absolutely nothing to organize anything.

Once again, with feeling, grouping by web site does absolutely nothing to organize anything in a useful way.  

If I'm looking for a job, say, and I want to have a tab group (the thingie that you colorize) that includes linkedin, and dice, and a company's careers page which, please note carefully,  ***are***all***in***different***website***domains***, to use this extension I would have to open a brand new chrome window and drag linkedin, dice, and the company's career page just into that one Chrome window.  Next thing you know, I have 20 Chrome windows open, one for each activity that I pursue.  

One whole Chrome window for job hunting, another whole Chrome window for roommate-finding, another whole Chrome window for diy projects around the house, etc.  If I follow the logic of this extension, I would have to open 20 Chrome windows and drag tabs into each one just to use the extension.

I'm overjoyed that the extension is useful for you, but I am trying (very hard) to suggest a missing capability that other people might find useful.

I am suggesting that you decouple the tab group (the thingie you colorize, currently) in your popup from the tabs that are in a Chrome window.

Let me create my own tab group within the popup.  Again, NOT a Chrome window, just an empty tab group.

Let me drag existing tabs into that new, empty tab group.  Say, let me drag a linkedin tab, a Dice tab, and a company's career tab into that new, empty tab group.

Again, the tab group does not represent a Chrome window, it represents a way of organizing tabs by function.  Like, my job-hunting function.

Such dragging and reorganizing should not (I say again, *n*o*t*) do anything to the Chrome window itself or the tabs therein.  No surprising new tabs, no tabs disappearing, no new Chrome windows I did not ask for.  Just organizing tabs into groups within the tab group (the thingie that you colorize) within your popup, and nothing else.

If you -then- want to give us the option of naming that new tab group within your popup, and I can name it, say, JobHunting then great.  But again, colorizing and naming does nothing to organize anything.  The functionality I'm suggesting actually performs an organizing service.

Despite my obvious frustration, I'm actually trying to help.

I don't think I could be any clearer.

If this falls on deaf ears then, screw it, I tried.

======== ps - example of what i mean ========

https://diyivorytower.files.wordpress.com/2011/10/2011_10_27-tab-group-screenshot.jpg

**Comment by demetrios-koziris** [comment]
Just my own 0.02 but decoupling how tabs are displayed in the extension (with your proposed "tab groups") from how they are organized in the browser (by window) would be a pretty strange prospect. One of the main purposes of the extension for me is to have a better interface for managing my tabs rather than having to access them through the standard chrome UI. 
If the extension doesn't reflect or change how things are actually grouped in the browser then it's simply a tab categorizer rather than a tab manager. Maybe you're looking for something more akin to a bookmark manager?

**Comment by mastef** [comment]
> What in the world is the use of having a tab group with the same old 100+ tabs all in one place? Nothing.
> 
> I already have something that shows me that - chrome itself.
> 
> Don't need an extension to show me "Hey, here are your million unmanageable tabs, but hey, they're sorted by website".
>
> People sort tabs not by website, but by function.

Please be aware : This extension _does not_ sort any tabs by website.

It shows all currently open ( and minimized ) windows with their tabs in one consolidated view. Chrome doesn't offer such a view, hence the need for this extension.

![image](https://user-images.githubusercontent.com/762297/41654104-8933d2a0-74b2-11e8-9a64-10e54ab3ced3.png)

It should show them in the same way as you have them open in your Chrome windows. ( If it _does_ sort them, then please let me know and that would be a potential bug ).

> For example, I'd love a tab group for, say, "Programming" into which I can manually move github, hackerrank, codeacademy, and youtube training videos. All different websites, but in one meaningful tab group. See what I mean?
 
> Naturally, i would not want these tab groups to ruin the way I've got them arranged in chrome itself. Just something that allows me to create little tab groups, drag icons around, etc; same functionality as in the hardcoded not-so-useful "everything" single tab group you have now.

So what you're asking for atm is a completely separate logic layer - decoupled from windows and tabs. I understand what you're saying - but please be aware that that's not the purpose of this Tab Manager.

As I mentioned yesterday already in my "off-the-mark suggestions" - you might be better of with [Toby](https://www.gettoby.com) - that's more of a tab bookmarker / session manager / tab categorizer. Have you tried it?

> I was two seconds from uninstalling this extension and giving it a review, but it is sooooo close to what I need I thought I'd give this a shot.

So you're looking for functionality A, but you install an extension that advertises functionality B - and then you'd give it a bad review for that? Don't be _that_ guy.

Tab Manager is a fork of a popular extension that has been like this for many years ( it has been removed from the web store as the original author filled his version with malware ), and it is - contrary to your statements - actually very useful. It just doesn't do what you think it _should_ do in your opinion. And that's fine.

You can fork it and add that functionality yourself. Just be aware that it'd be a bigger rewrite. Or try first some other extensions that actually advertise tab categorisations - I suggested Toby above, but there might be some others that can do something similar.

Good luck!

**Comment by GreatAlfredini** [comment]
> demetrios-koziris:
> One of the main purposes of the extension for me is to 
> have a better interface for managing my tabs 

Sure, but you could have it both ways.  

There is no law that says you have to use "my" feature, the one I suggest.

You could continue to use the extension as you always have, without ever creating any new empty tab groups.

> your proposed "tab groups") from how they are organized in 
> the browser (by window) would be a pretty strange prospect

Strange?  Harrumph.  Well, one of the most wildly successful browser features did this, even if it was a strange, bizarre, Kafka-esque, vertigo-inducing feature.  Millions of strange people loved it.

Unfortunately, 1) it was for Firefox and 2) it's been discontinued.

Earlier I linked to an image showing the feature at work.  So nobody has to scroll up, here is the link again:
https://diyivorytower.files.wordpress.com/2011/10/2011_10_27-tab-group-screenshot.jpg

> mastef:
So you're looking for functionality A, but you install an extension that advertises functionality B - and then you'd give it a bad review for that? Don't be that guy.

Right, as a developer myself I would always want to be fair.

The reason I thought it had functionality B is that it calls itself a "Tab Manager".  In my experience many extensions that call themselves Tab Managers offer functionality B, but very poorly.

So, I thought, "Yikes, this extension claims to call itself a tab manager, but it doesn't let me manage my  tabs my way at all".

However I loved the UX and it seemed so close to my ideal, I thought I'd suggest it.

Personally, I'd call it more like "Chrome window manager plus", the plus being the ability to drag tabs from window to window.  "Tab Manager" sounds like functionality B to my ears.

> You can fork it and add that functionality yourself. Just be aware that it'd be a bigger rewrite.

Have never developed an extension, there might be a pull request from me one day. 

Not having looked at the code, I would have figured it would not require a rewrite but some additional modules, but I speak without knowing the code.

> I suggested Toby above, but there might be some others that can do something similar.

Thanks, will try it.  

It doesn't look like my suggestion is getting much love, people use it as-is, so I will flounce off to search the Chrome store, perhaps adjusting my search term to "tab categorizer", thanks again for the suggestion.

**Comment by mastef** [comment]
@GreatAlfredini You might also have some luck by recovering the old Firefox extension and refurbishing it to work as a Chrome extension. The new Firefox add-ons API and the Chrome extensions API are basically identical.

So it'd be just a matter of porting [the old Firefox extension's code to the new Firefox API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on). From there it's a tiny jump to have it available as Chrome extension.

I understand your frustration about the term "Tab Manager". It is indeed ambiguous and can have multiple meanings.

The rewrite would be mainly since you'd want to remove windows and the windows logic, and save the tab groups somewhere in chrome.storage. Also some additional logic for when you close tabs, and re-open tabs ( should they remember which group they were in? ). And if you have tabs with similar URLs ( e.g. Github ) that you actually want to store in multiple groups. ( Maybe regex )

I do appreciate you taking the time for this suggestion. Please feel free to re-open this issue if you have a PR or a ported fork of the old extension somewhere.
