### ISSUE TITLE
enhancement: "Name The Window" field reflected on Windows Taskbar (Window Title)

### ISSUE THREAD

**Issue by brain8891** [stefanXO/Tab-Manager-Plus#32]
Example: 
when you rename it to "Main":
![image](https://user-images.githubusercontent.com/7104190/68687716-07ee4100-0587-11ea-8207-9682c11b5c25.png)
It would reflect the same title on Windows Taskbar:
![image](https://user-images.githubusercontent.com/7104190/68687780-281e0000-0587-11ea-8b48-16960bd3286b.png)

Is it possible? There is this addon that uses Webextension API, to change the window Title in firefox:
https://addons.mozilla.org/en-US/firefox/addon/window-titler/?src=search
![image](https://user-images.githubusercontent.com/7104190/69448073-3df2a880-0d71-11ea-8448-630c45d39c6f.png)

Why have this feature?
It helps the user to navigate between different windows much faster, especially when the windows get rearranged when Firefox restarts.

example:
![image](https://user-images.githubusercontent.com/7104190/68688058-919e0e80-0587-11ea-86c5-7b06f4a8558c.png)

Thank you for your hard work

**Comment by Jonta** [comment]
Why was this closed?

I was going to suggest compatibility with the extension @brain8891 mentions

**Comment by mastef** [comment]
> Why was this closed?
> 
> I was going to suggest compatibility with the extension @brain8891 mentions

It should be implemented in Firefox already

**Comment by mastef** [comment]
> Why was this closed?
> 
> I was going to suggest compatibility with the extension @brain8891 mentions

@Jonta it should be implemented already in 5.2.0

**Comment by Jonta** [comment]
Ah, nice!

Note: Disable Window Titler

Otherwise, you'll name a window in TMP, and the name will disappear when you open a new tab
