### ISSUE TITLE
Cannot change shortcut in firefox

### ISSUE THREAD

**Issue by Applemann** [stefanXO/Tab-Manager-Plus#33]
In Firefox when I want to change default shortcut so the link in preferences open this: 
![image](https://user-images.githubusercontent.com/2686906/68690714-cbb0e580-0572-11ea-9275-8d4ec4c70cf0.png)

And I cannot change it anywhere..
I have Firefox 68.0

**Comment by mastef** [comment]
Thanks @Applemann - I need to add a better help text there. This is how you can change the short cut on that page : 

![image](https://user-images.githubusercontent.com/762297/68735624-e0dc5180-0610-11ea-8a7c-ffb33c8ad13c.png)

**Comment by mastef** [comment]
The helptext actually says it, but I myself just missed it as well. Need a screenshot there

![image](https://user-images.githubusercontent.com/762297/68735734-213bcf80-0611-11ea-906f-1d79fc1b3cd6.png)

**Comment by Jonta** [comment]
The [Change shortcut key]-link seems to do nothing, which is confusing. If it can't, I suggest not having it be a link.

```
TMP 5.1.4
Firefox 75.0
macOS 10.11.6
```
