### ISSUE TITLE
Current Tab button

### ISSUE THREAD

**Issue by sapioit** [stefanXO/Tab-Manager-Plus#4]
Hi,

I have 1735 tabs currently opened (will revert back to about 1400 in a few days, and then reduce their numbers even more, but slowly). As you could probably imagine, it's rather difficult to keep tab (bad pun intended) of the active tab (the tab you're currently active in). 

As such, I would like to request to add a button which, when pressed, shows the active tab in the view of the mod's popup. I know HTML has the `<a href="#sth">go</a> to <a name="sth">here</a>` which lets one "jump" from `a href` to the [`a name`](https://www.w3schools.com/tags/att_a_name.asp), so I thought something similar might be doable for this extension, too.

Such a button would remove the need to scroll through the whole list looking for the `[Active]` tag.

Thanks in advance!

**Comment by mastef** [comment]
Hi there! Do you mean "jump to active" per window, or "jump to active" for all windows?

**Comment by sapioit** [comment]
Per window. Each window has a tab that is selected/active. You could add the button to loop through each active tab, for easier access to the tabs nearby the active tab.

**Comment by sapioit** [comment]
I mean, I now have 2206 tabs (subject to reduction to about 2100 in the near future), and it would be nice to just press a button and have the extension scroll automatically to where the current tab is.

Now that I think about it, you might know which window the extension extension's tab list is opened in, so you could have it scroll to the current active tab in the current active window, to make things easier.

**Comment by mastef** [comment]
@sapioit in the current version the app will automatically scroll to the active tab. Let me know if that works for you.

**Comment by sapioit** [comment]
It works, thank you!
