### ISSUE TITLE
Deceptive Site Ahead

### ISSUE THREAD

**Issue by bioye** [stefanXO/Tab-Manager-Plus#43]
Suddenly started getting **Deceptive Site Ahead** warning earlier today.  Which means I'm totally unable to use this extension which I can't live without.

<img width="1428" alt="Screenshot 2019-12-10 at 11 32 22 PM" src="https://user-images.githubusercontent.com/19975295/70574873-71249c80-1ba5-11ea-83cd-4705e584f3af.png">

**Comment by mastef** [comment]
Wow , are you sure this is from my plugin and not from something else? There shouldn't be anything like this inside this tab manager... Have you tried installing it fresh from scratch? You can try a version here : https://github.com/stefanXO/Tab-Manager-Plus/releases

Make sure your system isn't infected with spyware / virus

**Comment by mastef** [comment]
Is it possible you have a tab open with that url? Maybe the favicon from that website is triggering this warning

**Comment by bioye** [comment]
Thanks for that.  You are correct.  The url was trying to steal my Apple ID details.  Will have to update the password again.  Thank you.

<img width="1440" alt="Screenshot 2019-12-11 at 10 39 57 AM" src="https://user-images.githubusercontent.com/19975295/70609882-dd81b900-1c02-11ea-8405-cd9aebedf6ec.png">

**Comment by mastef** [comment]
Should be additionally fixed in the future by switching to the browser favicon api
