### ISSUE TITLE
Scrolling causes tabs to be hidden

### ISSUE THREAD

**Issue by jro79** [stefanXO/Tab-Manager-Plus#48]
When I have at least one window minimized and I scroll through my open tabs using this extension, the open windows disappear/are hidden as I scroll down, reappearing once I get to the bottom of the list where the minimized window is shown.  They also intermittently disappear/reappear when I move the cursor over the minimized and maximized windows.
When switching between active tabs on different windows, the app also did not switch back to the desktop where the other active window was.  When I manually switched, the firefox window had been shrunken so the title of the page was the only thing visible.

![Scroll 1](https://user-images.githubusercontent.com/26385927/72356287-04765380-36b7-11ea-852c-777fc73e510e.png)

![Scroll 2](https://user-images.githubusercontent.com/26385927/72356290-05a78080-36b7-11ea-9e78-f76fc1a9787a.png)

![Scroll 3](https://user-images.githubusercontent.com/26385927/72356292-06d8ad80-36b7-11ea-8700-b9a90c2a896a.png)

**Comment by mastef** [comment]
Do you mind testing this with this version please 
[tab-manager-plus-5.1.5.firefox.zip](https://github.com/stefanXO/Tab-Manager-Plus/files/4513183/tab-manager-plus-5.1.5.firefox.zip)

( Instructions on how to install in this comment : https://github.com/stefanXO/Tab-Manager-Plus/issues/65#issuecomment-616348799 )

**Comment by mastef** [comment]
This should be now fixed in the latest 5.1.5 version that has been released. If not, please re-open this issue
