### ISSUE TITLE
Problem - Export Configuration not functioning

### ISSUE THREAD

**Issue by Steve24959** [stefanXO/Tab-Manager-Plus#49]
The JSON file that is exported is empty.

Firefox - 72.0.1
Tab Manager Plus - 5.1.3

**Comment by mastef** [comment]
Hi @Steve24959 - there is no function to export the configuration. There is only a function to export saved sessions. Are you sure you have saved some windows before using the export function?

**Comment by Steve24959** [comment]
I meant saved windows. No, I am not certain I saved them first. Do I save each individual window and then do an export?

- Steven

**Comment by mastef** [comment]
So we have the "star icon" in each window, which allows you to save windows for later : 
![image](https://user-images.githubusercontent.com/762297/72574288-10525780-38fb-11ea-8668-e61d2f0d9fcb.png)

Then they'll show up in the bottom area called "Saved windows" :
![image](https://user-images.githubusercontent.com/762297/72574302-1a745600-38fb-11ea-9e91-05771697da8c.png)

Then once you export the file with this option : 
![image](https://user-images.githubusercontent.com/762297/72574449-ab4b3180-38fb-11ea-9de1-baeb85e2e195.png)

You should receive a json file with all your saved windows in it :
![image](https://user-images.githubusercontent.com/762297/72574383-7343ee80-38fb-11ea-9972-9b994409c19a.png)

**Comment by mastef** [comment]
@Steve24959 let me know if this resolved your issue. I'm going to close this for now, but if the issue persists please feel free to re-open.
