### ISSUE TITLE
Fuzzy search/filtering

### ISSUE THREAD

**Issue by marnovo** [stefanXO/Tab-Manager-Plus#55]
Does the extension support fuzzy search/filtering? If not, any plans to implement it? Thanks!

E.g.: if I have a tab named "Tab-Manager-Plus", I can type "tab pl us" and the search would still match this tab.

For a practical example, check the https://github.com/janraasch/tab-ahead which uses https://github.com/krisk/fuse

**Comment by mastef** [comment]
Should be now possible in 5.2.0. Comes with support for `OR` and `tab pl us`
