### ISSUE TITLE
CMD-M Keyboard Shortcut Not Working (Mac OS)

### ISSUE THREAD

**Issue by drdannysands** [stefanXO/Tab-Manager-Plus#6]
Keyboard shortcut on Mac supposed to be Command-M, but this performs a minimize current window action on Mac and I can't see way to change this. Your "Change keyboard shortcut" link on preferences screen does not let me change shortcut as far as I can see.

Thanks.

**Comment by mastef** [comment]
Hi @drdannysands 

The shortcuts in the latest version are `Ctrl+Shift+M` for Windows, and `Command+Shift+M` on Mac OS. You should also be able to change the shortcuts here : chrome://extensions/shortcuts

Let me know if that works for you

**Comment by drdannysands** [comment]
​​
Thank you. That works.

**Comment by Jonta** [comment]
Suggesting more prominence for the shortcut. I didn't know about it until I saw this issue (because I was going to create my own issue "why isn't there a keyboard shortcut to activate this extension)
