### ISSUE TITLE
Tab limit can be exceeded

### ISSUE THREAD

**Issue by stephanedaviet** [stefanXO/Tab-Manager-Plus#62]
I have installed your extension that has been really helpful to cure my tab addiction and close hundreds of them :-).

I have set a tab limit but I encounter a bug: it seems that I can open more tabs than this limit.

Steps to reproduce:
- Set a tab limit to `n`,
- Open `n` tabs,
- Open one more tab, it opens in a new window,
- Quickly go back to the first window and open another tab, it will often open in the first window, exceeding the number of tabs allowed for this one.

I think it comes from the way you handle tab opening : https://github.com/stefanXO/Tab-Manager-Plus/blob/master/lib/background.js#L79-L92, perhaps the fact that it is asynchronous. I previously use https://addons.mozilla.org/en-US/firefox/addon/max-tabs-web-ext which doesn't exhibit this problem. I have looked at their code which is quite different : https://github.com/kanru/max-tabs/blob/9907b10934145f1d6840995ce6216755ed8feb62/background.js#L44-L64.

Have you encountered this problem?

**Comment by mastef** [comment]
Hi @stephanedaviet - are you by any chance using firefox? There seem to be many issues due to async in firefox currently.

**Comment by stephanedaviet** [comment]
Exactly, I'm using Firefox. Is the async needed? I'm currently using both your extension to better manage my tab addiction :-) and the aforementioned Max Tabs and this last doesn't exhibit this bug while not using asynchronicity either.

**Comment by mastef** [comment]
The big issue is that based on another release ( https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/5.0.6 ) we have added backwards compatibility for older browsers. But that does seem to mess up the async functionality in Firefox at least...

So I'm thinking about dropping the old browser support as it comes with too many issues...

@stephanedaviet If I upload here another version in this ticket, would you be able to check if you're still encountering the issue?

**Comment by stephanedaviet** [comment]
> If I upload here another version in this ticket, would you be able to check if you're still encountering the issue?
For sure.

I don't really understand the link between support of old browsers and async :smiley:. Looking at commits for the 5.0.6, I saw the introduction of a `async` in `background.js` that was not used before. I suppose this is what you mean?

**Comment by mastef** [comment]
@stephanedaviet right, but with 5.0.6 the dist code is being compiled through babel, so babel does some old browser compatible magic with async/await, converting them to some other type of wrapper. And I think that is failing on Firefox for some reason.

**Comment by mastef** [comment]
For example the source code says `await browser.tabs.remove()` here https://github.com/stefanXO/Tab-Manager-Plus/blob/master/lib/TabManager.jsx#L617-L633

But the dist code has an _asyncToGenerator with a `regeneratorRuntime.mark` and `switch` statements. I think it's not working as it should in FF extensions. https://github.com/stefanXO/Tab-Manager-Plus/blob/master/outlib/TabManager.js#L636-L661

So what I can propose is to compile a `only modern browsers` version for you, you can load it in your Firefox and see if it solves your issue?

**Comment by mastef** [comment]
@stephanedaviet you can add this at `about:debugging#/runtime/this-firefox` "Load Temporary Add-on..." and see if it fixed it for you.
[tab-manager-plus-5.1.3.firefox.zip](https://github.com/stefanXO/Tab-Manager-Plus/files/4484785/tab-manager-plus-5.1.3.firefox.zip)

**Comment by mastef** [comment]
The only way for this to happen ( from what I can see currently ) is if you're not opening the new tab as last tab in that window, but somewhere in the middle.

I have really tried to reproduce your case, but so far had no luck. The new tab always gets moved to a new window. ( Tab limit set to 6 in this case, testing on Windows 7 + FF 75 )

![image](https://user-images.githubusercontent.com/762297/79823461-17877680-83be-11ea-92f6-38a3ddfb1284.png)

I reviewed the other extension, and they are also using an async approach. The only difference in their approach is that they're checking the tabs length from the current window, whereas here we were comparing the tab index.  

If you're still encountering this issue @stephanedaviet, then you can check if that works for you now in this version :
[tab-manager-plus-5.1.5.firefox.zip](https://github.com/stefanXO/Tab-Manager-Plus/files/4507583/tab-manager-plus-5.1.5.firefox.zip)
