### ISSUE TITLE
Support ctrl+p/n to navigate the tab list

### ISSUE THREAD

**Issue by needfaster** [stefanXO/Tab-Manager-Plus#63]
Thanks for the amazing extension, love it.

Currently it uses the arrow up/down shortcut to navigate the tab list. It is very hard to use the arrow up/down in some keyboard, or for keyboard person.

Suggestion: supporting the ctrl+p and ctrlp+n to navigate the tab list, at least make it configurable.

**Comment by needfaster** [comment]
no

**Comment by Jonta** [comment]
> no

Why not?
