### ISSUE TITLE
Searchbar doesn't turn dark in darkmode

### ISSUE THREAD

**Issue by Jonta** [stefanXO/Tab-Manager-Plus#67]
```
TMP 5.1.4
Firefox 75.0
macOS 10.11.6
```

**Comment by mastef** [comment]
Please submit a screenshot. Or do you mean that the searchbar background is white?
![image](https://user-images.githubusercontent.com/762297/79927930-88389c80-846b-11ea-94e1-5396d1766575.png)

**Comment by Jonta** [comment]
I mean that the searchbar background is white. (And that the text we type in it is dark)
