### ISSUE TITLE
Graphics glitch scrolling down to minimised tabs in popup (vertical view only)

### ISSUE THREAD

**Issue by Jonta** [stefanXO/Tab-Manager-Plus#68]
Happens in both light- and dark-mode

Dark mode:

![image](https://user-images.githubusercontent.com/359397/79884370-63094700-83f5-11ea-9fd6-e2ee570fda94.png)

About 150 tabs, in 16 windows. Tested and reproduced in a fresh Firefox-profile as well.

```
TMP 5.1.4
Firefox 75.0
macOS 10.11.6
```

Possibly related: https://github.com/stefanXO/Tab-Manager-Plus/issues/48

**Comment by mastef** [comment]
Do you mind testing this with this version please 
[tab-manager-plus-5.1.5.firefox.zip](https://github.com/stefanXO/Tab-Manager-Plus/files/4513183/tab-manager-plus-5.1.5.firefox.zip)

( Instructions on how to install in this comment : https://github.com/stefanXO/Tab-Manager-Plus/issues/65#issuecomment-616348799 )

**Comment by mastef** [comment]
@Jonta I see you added a lot of issues since my last comment. Please can you check if the version I attached fixes the issue for you

**Comment by Jonta** [comment]
> @Jonta I see you added a lot of issues since my last comment. Please can you check if the version I attached fixes the issue for you

I will, and I'll update the issues then. I'm prioritising _using_ the extension now. Should only be a few days

**Comment by mastef** [comment]
This should be resolved now in the latest 5.1.5 - if not please re-open.

**Comment by Jonta** [comment]
Seems like the fix worked. =)
