### ISSUE TITLE
Maximize button on entry in "minimized windows" list in Tab-Manager-Plus popup does not work on Linux

### ISSUE THREAD

**Issue by equalsJeffH** [stefanXO/Tab-Manager-Plus#7]
Maximize button on entry in "minimized windows" list in Tab-Manager-Plus popup does not work on Linux (for me anyway) yet it does seem to work on Windows 10.

Linux version is essentially current Debian Testing.

**Comment by mastef** [comment]
Thanks for the report @equalsJeffH - do you mean that hovering over a tab icon, does not increase the size of the tab icon? Is that what you mean?

Default view
![image](https://user-images.githubusercontent.com/762297/48457180-517d4200-e7f4-11e8-9c3e-9c09e8178525.png)

With mouse hovering over the tab
![image](https://user-images.githubusercontent.com/762297/48457208-6659d580-e7f4-11e8-8d08-79da1c9d7007.png)

Do you have Animations enabled in the settings?
![image](https://user-images.githubusercontent.com/762297/48457257-91442980-e7f4-11e8-8a98-ddc81ffe9be6.png)

**Comment by equalsJeffH** [comment]
@mastef wrote:
> do you mean that hovering over a tab icon, does not increase the size of the tab icon? Is that what you mean?

sorry, no.  I mean (in my Debian-testing based linux) if you have both minimized and maximized browser windows, then in an open browser window click on the tab-manager-plus (TMP) extension icon in the browser tool bar, and in the TMP popup then scroll down to the list of "minimized windows", then hover the mouse pointer over the little green up-arrowhead button in the set of four icons on the right-hand side of each listed minimized window (the tooltip says "Maximize this window [...]", and then click that green button, nothing happens. 

Whereas on windows 10, it will maximize the window in question. 

does that help? sorry, my screenshot fu is very poor and do not have time to try to put screenshots in here...  

on windows TMP is great and I wish it to work as well on linux.

thanks!

**Comment by mastef** [comment]
Ah, so simply "maximize this window" doesn't work on Linux, right? Gonna check :)

**Comment by mastef** [comment]
I think there are some issues with maximizing windows on unix recently https://bugs.chromium.org/p/chromedriver/issues/detail?id=1901 and https://github.com/SeleniumHQ/docker-selenium/issues/559

I'm not sure this is related. Which Chrome version are you using there?

**Comment by mastef** [comment]
I can see that Chrome on Debian has issues with "maximize" and "normal" states. Some regressions...

You could maybe test it with Chrome Canary ( or Chrome default - depending on which you are using ), or an earlier version, and see if that works? Possibly a Chrome bug on unix.

A quick search has shown me a few people reporting issues with changing windows state ( which we're doing here ) on Unix systems.

**Comment by equalsJeffH** [comment]
@mastef, thanks for checking on this -- I'm on chrome Version 70.0.3538.102 (Official Build) (64-bit). 

I'll see about trying beta/canary.

> A quick search has shown me a few people reporting issues with changing windows state ( which we're doing here ) on Unix systems.

outta curiosity, which search engine and search terms did you use?  thx again!

**Comment by equalsJeffH** [comment]
@mastef -- i tested the dev channel linux build and it is exhibiting the same sub-optimal behavior of not opening minimized windows :(

I wonder if other extensions are running into the same problem...

**Comment by equalsJeffH** [comment]
HI @mastef -- yes, I'll try your suggestion above in a day or few -- my day job has been in the way lately, please stand by...

**Comment by mastef** [comment]
@equalsJeffH did you ever get to test this? And if the issue still persists, please let me know. I'll close this ticket until then.

**Comment by equalsJeffH** [comment]
Hi @mastef -- I am reporting that this bug got actually, really resolved somehow over the past few weeks. I am unsure whether the resolution is due to fixes in OS+libs or in tabManagerPlus update(s) or what, but anyway, maximize now works which is quite helpful. thanks much for your great extension.
