### ISSUE TITLE
Req: Progress indicator when opening popup 

### ISSUE THREAD

**Issue by Jonta** [stefanXO/Tab-Manager-Plus#75]
No progress indicator when opening the popup. Just sits there and seems to do nothing for a while (147 tabs, 16 windows)

I suggest an animated spinning thing

Related: https://github.com/stefanXO/Tab-Manager-Plus/issues/36

```
TMP 5.1.4
Firefox 75.0
macOS 10.11.6
```

**Comment by mastef** [comment]
So the popup shouldn't take longer than a second to open... is the first open slow? Or every open of the popup?

**Comment by Jonta** [comment]
Tried and failed reproducing with 5.1.6 now, and a whole bunch of blank tabs

It was signficantly longer than a second every time, with content, in 5.1.4

Tabs with actual content might reproduce it in 5.1.6

**Comment by mastef** [comment]
Ok, please re-open if you can reproduce
