### ISSUE TITLE
Naming a window, then hitting enter opens a new window instead of closing the title popup

### ISSUE THREAD

**Issue by Jonta** [stefanXO/Tab-Manager-Plus#78]
- TMP-tab
- Rename a window
- Type in name
- Hit Enter-key
- New window opens, instead of confirming the name change
- [Confused software noises]

Clicking the X in the upper right corner works, but UI-wise is much closer to "Cancel"

Tested in a TMP-only Firefox-profile

```
TMP 5.1.4
Firefox 75.0
macOS 10.11.6
```

**Comment by benkloester** [comment]
I am also experiencing this.
