### ISSUE TITLE
Feature Request: Copy Highlighted Tabs to Clipboard (Title + URL in HTML format)

### ISSUE THREAD

**Issue by YipYipX4** [stefanXO/Tab-Manager-Plus#8]
Hi,

Thank you for this great extension!

I would like to request a small feature to copy all of the highlighted tabs to the clipboard in HTML format, with the tab title as the link text.

Use cases:

1. Any time I want to copy an ugly URL to an email or other document, I have to copy the URL from the address bar, then manually edit the display text to something reasonable.  Alternatively, I can sometimes click "back" to find the original link (e.g. Google search results), then copy & paste that link in HTML format.
2. Many users may want to archive highlighted tabs by copying links to some document (such as OneNote), followed by closing all of the highlighted tabs (for this reason, the highlighted tabs should remain highlighted after clicking "copy to clipboard").

Implementation Note:

For each highlighted tab, you could use the following template (the target="_blank" opens links in a new tab, and could be an optional feature):

```html
<a href="{url}" target="_blank">{title}</a><br/>
```

I think this would be very useful for a lot of people (and probably easy to implement).  I am aware that there are other extensions that do exactly this feature, but only for the current tab or all tabs.  If the feature is added to this extension, then users can search or manually highlight specific tabs and copy only the desired tabs to the clipboard (and we wouldn't need yet another extension for a small feature).

Thank you for considering my request!

**Comment by mastef** [comment]
Hi @YipYipX4 - I would have to refer you to this extension for now : https://chrome.google.com/webstore/detail/tabcopy/micdllihgoppmejpecmkilggmaagfdmb?hl=en-US

Which currently works with "all tabs", "current window", "current tab". I would reach out to their dev to add a checkbox so you can select specific tab groups.

OR :  Fork a version of tab manager plus and add it yourself.

But at this stage I don't think that this would be a feature most of the users would benefit from, and we have already a lot of buttons in there. Have to keep it light, sorry.
