### ISSUE TITLE
Search does not open window with desired tab.

### ISSUE THREAD

**Issue by Migotes** [stefanXO/Tab-Manager-Plus#82]
Can you recreate the problem?:
1. click on Tab Manager Plus. 
2. search for the desired tab. 
3. confirm the found tab with click on enter. 
4. the window with the desired tab does not come to the foreground.

When I click with the mouse on the found tab the window comes to the foreground. It seems to be a problem with the confirmation by click on enter.

My OS is Windows 10 with Firefox 75.0.

**Comment by mastef** [comment]
Cannot confirm on Mac, so I think this will be related to similar behaviour as in #65 and https://bugzilla.mozilla.org/show_bug.cgi?id=1631664

Thanks for reporting

**Comment by mastef** [comment]
Just making sure - this is with the official version 5.1.5?

**Comment by Migotes** [comment]
Yes – with Version 5.1.5. 

 

How can this be tested under Windows:

 

1.	Open a new window with (for instance) the following URL: https://www.bbc.com/
2.	Open another new window with the follwing URL: https://edition.cnn.com/
3.	Click in the CNN-Window on Tab Manager Plus and type „bbc“: BBC is selected.
4.	Press the key ENTER to switch to the window with the BBC tab.

 

It doesn’t work.

 

Another test:

 

1.	Open a new window with (for instance) the following URL: https://www.bbc.com/
2.	Open another new window with the follwing URL: https://edition.cnn.com/
3.	Click in the CNN-Window on Tab Manager Plus and type „bbc“: BBC is selected.
4.	Click the mouse button on the selected tab to switch to the window with the BBC tab.

 

It works.

 

Kind regards,

Michael

 

 

Von: Markus Stefanko <notifications@github.com> 
Gesendet: Montag, 27. April 2020 12:05
An: stefanXO/Tab-Manager-Plus <Tab-Manager-Plus@noreply.github.com>
Cc: Migotes <mtesch@wtnet.de>; Author <author@noreply.github.com>
Betreff: Re: [stefanXO/Tab-Manager-Plus] Search does not open window with desired tab. (#82)

 

Just making sure - this is with the official version 5.1.5?

**Comment by mastef** [comment]
Yeah, it works for me flawlessly in the latest 5.1.5. Thanks, I'll test it in a VM

**Comment by mastef** [comment]
I cannot reproduce it on 5.1.5 for Firefox on Windows 🤔 

I hope you have the latest 5.1.5 from the add-ons store ( https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/ ) and not an earlier version from one of the github issues we tested with...

**Comment by Migotes** [comment]
This is strange... I can reproduce this with all our Windows-PC's and 
Tab Manager Plus 5.1.5 from add-ons store (which do you mean). This 
problem appears with Firefox 75.0 and 76.0b8.

Mmmhhhh....


Am 27.04.2020 16:32, schrieb Markus Stefanko:

**Comment by Migotes** [comment]
Note: Do you press ENTER not click with the mouse?



Am 27.04.2020 16:32, schrieb Markus Stefanko:

**Comment by mastef** [comment]
Hm, yes. FF 75 on Win 7 in this case :

![firefoxwindows](https://user-images.githubusercontent.com/762297/80389242-0e723a00-88d5-11ea-98a5-b1d5a4d95cef.gif)

**Comment by Migotes** [comment]
You have to test with different windows not tabs. Please see my test 
instructions described here on github above.

Am 27.04.2020 17:20, schrieb Markus Stefanko:

**Comment by mastef** [comment]
Thanks for verifying - was related to the same FF bug. Should be fixed now in 5.1.6
