### ISSUE TITLE
Allow setting a title for a group of tabs

### ISSUE THREAD

**Issue by yoni-lemonade** [stefanXO/Tab-Manager-Plus#9]
It would be great if instead of having titles such as "google, gmail & 4 more", a user would be able to set a title for these tabs group, for easier orientation.

**Comment by mastef** [comment]
@yoni-lemonade hi there, you can already do that yourself. Click on the "Colorize this window" button, and you can set your own custom color background and title

**Comment by yoni-lemonade** [comment]
Oh, haven't noticed that, perfect, 10x!
