### ISSUE TITLE
Suggestion: In Settings: Stating what happens when max tabs is exceeded

### ISSUE THREAD

**Issue by Jonta** [stefanXO/Tab-Manager-Plus#90]
I've seen tab blockers that just refuse opening a tab, which was what I expected to happen here, instead of the tab being pulled to new window
```
TMP-only Firefox-profile
TMP 5.1.6
Firefox 75.0
macOS 10.11.6
```

**Comment by mastef** [comment]
The option description already states what happens when max tabs are exceeded.

![image](https://user-images.githubusercontent.com/762297/80933254-2540f100-8ded-11ea-9175-2595f0397995.png)
