### ISSUE TITLE
Tips: Don't show tips for features I've already used

### ISSUE THREAD

**Issue by Jonta** [stefanXO/Tab-Manager-Plus#92]
There should probably be a threshold for this (I'm sure there are some best practices out there), but if I've used this feature (e.g. right click to select tab) A Lot™ already, don't give me that tip.

Maybe have a place that contains all tips. [There aren't that many atm](https://github.com/stefanXO/Tab-Manager-Plus/blob/8cf03635bf4e1d4e01fa8b5aa517b80598e7a1ef/outlib/TabManager.js#L1616).

```
TMP-only Firefox-profile
TMP 5.1.6
Firefox 75.0
macOS 10.11.6
```

**Comment by mastef** [comment]
Tips are simply non-obtrusive fillers for the 2nd title - and while you may have already used a feature once, you might have forgotten about it a few months down the road.

I'm not really into overcomplicating a filler feature currently. If we'd have 30 of them - maybe. But even then it would be overkill to track plugin usage just to filter out fillers.

I suppose more tips would be something that could be done instead.
