### ISSUE TITLE
Shift-Rightclick doesn't work on Firefox

### ISSUE THREAD

**Issue by robertmaxton42** [stefanXO/Tab-Manager-Plus#94]
The addon options page indicates that it should be possible to select or deselect all tabs in a range by using shift-rightclick, but in Firefox at least this just opens the normal right-click menu. Shift-leftclick and shift-middleclick don't do anything either.This makes it very annoying to deal with large groups of tabs; I have literally thousands of tabs I'd like to group and I'd rather not have to click on every one of them. >.>

Thanks for keeping this updated!

**Comment by mastef** [comment]
Ok, I can reproduce it on Firefox. For now you can try selecting many tabs by right clicking on one, and then `shift`+`left/right` ( or `up/down` if you're in the vertical view )

**Comment by wadawada** [comment]
also not working on chrome
