### ISSUE TITLE
Export backup session saves empty file

### ISSUE THREAD

**Issue by benkloester** [stefanXO/Tab-Manager-Plus#98]
The experimental feature to save a session has never worked for me. I enable it, but the json file it saves is always a 2 byte file containing only.
`[]`

I noticd this when I tried to import from it - I got the error "Error: Could not restore any windows from the backup file!", and when I investigated I found it to be because the backup contained nothing, and making backups to test it also saved nothing.

**Comment by benkloester** [comment]
I'm on Tab Manager Plus 5.1.3 on Chrome version 83.0.4103.61 (Official Build) (64-bit)

**Comment by mastef** [comment]
@benkloester have you saved any windows before exporting them? 

By pressing this star icon when "Save windows for later" feature is enabled:

![image](https://user-images.githubusercontent.com/762297/83113012-3978c500-a0f1-11ea-97eb-d8e4df0ecf26.png)

**Comment by benkloester** [comment]
No I hadn't! That's a pretty weird UX though tbh. Why do I have to star things for them to be backed up? I just want to back up all the work I've done organizing tabs into logically grouped windows and naming those windows. This is a lot of work, so not saving should be the exception, not the rule. 

All I want is something to fix these 2 problems:

1. losing my open windows/tabs if chrome closes unexpectedly (and it's recovery fails, as sometimes happens)
2. losing the names of windows if chrome closes unexpectedly

Essentially I want session-manager like functionality built in. I suppose I could use another extension that does session management but it wouldn't solve 2) for me.
